### ISSUE TITLE
Crashing 

### ISSUE THREAD

**Issue by xpol11** [SkyblockExtrasFreed/Minion-Packet-Multiplier-Dupe#2]
Whenever i use this mod i get this error

The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderException: java.lang.VerifyError: Stack map does not match the one at exception handler 50
Exit Code: -1

**Comment by SkyblockExtrasFreed** [comment]
fixed
